spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://hsae:tsp@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.20.35:3306/hsae8001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "{cipher}AQAKr74zYlRK21B3alQW3kdpkrnKMvWYo+grRIsAZm7OxwS0FrrafkgKOKSm490B4uLQfpQdE3cVYabBoQ01dyTYHV1kCTyYPCV/qguiJQNkyfK/VXLdx0T4zP7X2E5zt2tx2VgoSgnOlrOEerRbZjR5hNCY6SeEIFBCgc2gmAJMXc1xvIey2kxcHoxqXNJBRX05bpL6a+YFaXTD3nQWj8YpPy9tyJVUSfKoTnSLdXErWhv+TbXjL7JiKdnj4ve/pvxpdKRk4RoWKXIfUVbxVBVL6oquTjl11pIAgPhQRF7V6gM+pT20wiipy4PyNXr4rp/8zp3eLZ1+2vpShyQ+yL8+OgU/pl0/CnQ7t++93YkhwqOQShng6RrZVJBI53fFYXE="
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  application:
    name: microcloud-config-dept-client
---
server: 
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://hsae:tsp@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
spring:
  profiles: beta
  datasource:
    url: jdbc:mysql://192.168.20.35:3306/hsae8001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root=0514tsp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  application:
    name: microcloud-config-dept-client