spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://hsae:tsp@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.20.35:3306/hsae8001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root=0514tsp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  application:
    name: microcloud-config-dept-client
---
server: 
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://hsae:tsp@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
spring:
  profiles: beta
  datasource:
    url: jdbc:mysql://192.168.20.35:3306/hsae8001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root=0514tsp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  application:
    name: microcloud-config-dept-client